### ISSUE TITLE
Error while running examples

### ISSUE THREAD

**Issue by dlekshmi** [ICB-DCM/ODEMM#8]
Hi 

I want to use your tool for analysing dynamics from cytometry and am running into an error that I cannot understand.. 

While running the conversion example I get an error stating this: 
`Undefined function 'setdefault' for input arguments of type 'struct'.

Error in generateODEMM (line 73)
    options = setdefault(varargin{1},options);`

Thanks in advance and great work!

**Comment by LoosC** [comment]
Thanks for your interest! ODEMM uses PESTO (https://github.com/ICB-DCM/PESTO/) to perform the parameter estimation and for other functions it also uses the PESTO function setdefault. Please let me know if there are any further problems or questions. I am happy to help!

**Comment by dlekshmi** [comment]
Thanks. I am also unable to find the function: getParameterGuesses.m

**Comment by dlekshmi** [comment]
And this I think will be my last request for the example on intrinsic and extrinsic noise: modelDef_geneExp_changeinit for simulating the data.
